version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
       all-deps:
          patterns:
            - "*"
          update-types:
            - "major"
            - "minor"
            - "patch"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: "all"
    groups:
       all-deps:
          patterns:
            - "*"
          update-types:
            - "minor"
            - "patch"
