name: Make Docs

on:
  push:
    paths:
      - "script/make-docs/*"
      - ".github/workflows/*"
  # TODO: consider removing wait for Release job, or run Release dry_run on PRs
  # pull_request:
  #   paths:
  #     - "script/make-docs/*"
  #     - ".github/workflows/*"

jobs:
  make-docs:
    name: Make Docs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Make Docs
        run: |
          npm ci
          npx ts-node-script ./index.ts
        working-directory: ./script/make-docs

      - name: Wait for Release job
        uses: lewagon/wait-on-check-action@ccfb013c15c8afb7bf2b7c028fb74dc5a068cccc # v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: 'Release / Semantic Release'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Push changes
        run: |
          git add docs/*
          DOC_CHANGES=$(git diff --name-only --cached)
          if test "$DOC_CHANGES"; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -m 'docs: update docs'
            git push
          else
            echo "No doc changes made."
          fi
