name: test-npm-publish

on:
  push:
    paths:
      - "tests/npm-publish/**"
      - ".github/workflows/_test-npm-publish.yml"
      - ".github/workflows/npm-publish.yml"
  pull_request:

jobs:
  pack:
    strategy:
      matrix:
        node-version: [14, 16, 18]
    name: "Pack"
    uses: ./.github/workflows/npm-pack.yml
    secrets: inherit
    with:
      working-directory: ./tests/npm-publish
      node-version: ${{ matrix.node-version }}
      cache-dependency-path: tests/npm-publish/package-lock.json
      package-version: '1.0.${{ matrix.node-version }}'
      package-prerelease: ${{ github.ref_name != 'main' }}
      package-prerelease-tag: 'alpha'
      upload-artifact: true
      artifact-retention-days: 3
      NODE_OPTIONS: '--max-old-space-size=6144'

  publish-packed:
    strategy:
      matrix:
        node-version: [14, 16, 18]
    name: "Publish (Packed)"
    uses: ./.github/workflows/npm-publish.yml
    needs: pack
    secrets: inherit
    with:
      node-version: ${{ matrix.node-version }}
      registry-url: https://npm.pkg.github.com/
      scope: dawilk
      cache: npm
      cache-dependency-path: tests/npm-publish/package-lock.json
      cache-modules-path: ./tests/npm-publish/node_modules
      NODE_OPTIONS: --max-old-space-size=6144
      working-directory: ./tests/npm-publish
      download-artifact: true
      artifact-name: ${{ needs.pack.outputs.package-filename }}
      publish-version: ${{ needs.pack.outputs.package-version }}
      publish-prerelease: ${{ github.ref_name != 'main' }}
      publish-prerelease-tag: ${{ needs.pack.outputs.package-tag }}
      publish-access: public
      publish-dryrun: true

  publish-nopack:
    strategy:
      matrix:
        node-version: [14, 16, 18]
    name: "Pack"
    uses: ./.github/workflows/npm-publish.yml
    needs: pack
    secrets: inherit
    with:
      node-version: ${{ matrix.node-version }}
      registry-url: https://npm.pkg.github.com/
      scope: dawilk
      cache: npm
      cache-dependency-path: tests/npm-publish/package-lock.json
      cache-modules-path: ./tests/npm-publish/node_modules
      NODE_OPTIONS: --max-old-space-size=6144
      working-directory: ./tests/npm-publish
      download-artifact: false
      artifact-name: ${{ needs.pack.outputs.package-filename }}
      publish-version: "1.1.${{ matrix.node-version }}"
      publish-prerelease: ${{ github.ref_name != 'main' }}
      publish-prerelease-tag: alpha
      publish-access: public
      publish-dryrun: true
